### ISSUE TITLE
Error in pair

### ISSUE THREAD

**Issue by Skele-Skele** [nicholashc/uniswap-skim#1]
i either run it and get constant error in pair or it works. Im a little new to js, would you mind explaining why it occurs?
> skele-uniswap-skim@1.0.0 skim /home/skele/skele-uni-skim
> node ./scripts/skim.js

error in pair: 0x598e740cda7c525080d3fcb9fa7c4e1bd0044b34

**Comment by Skele-Skele** [comment]
im sorry if this is just stupid, ive tried figuring this out I just dont understand

**Comment by nicholashc** [comment]
That pair should return a valid result. 

It's likely a connection issue with your node. Are you running a local Ethereum node or using a service provider like Infura?

To debug with more information, I recommend logging the full error messages catch blocks.

**Comment by Skele-Skele** [comment]
Yes it was a simple connection issue LOL, thanks for fast response!
yet sorry for late reply I havent been checking emails

**Comment by Skele-Skele** [comment]
Do you mind helping me understand how to properly call the skim function? I cant find any documentation on it, im a little puzzled as to how it works.

**Comment by nicholashc** [comment]
<https://uniswap.org/docs/v2/smart-contracts/pair/>
